#!/bin/sh

# Default values
DATE="None"
MODE="'compile'"

# Parse arguments
while [ "$#" -gt 0 ]; do
  case "$1" in
    --date)
      DATE="'$2'"
      shift 2
      ;;
    --update)
      MODE="'update'"
      shift
      ;;
    --email)
      MODE="'email'"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

cd scripts
python3 -c "from main import main; main($DATE, $MODE)"
