#!/bin/sh

# Default values
DATE="None"
UPDATE_ONLY="False"

# Parse arguments
while [ "$#" -gt 0 ]; do
  case "$1" in
    --date)
      DATE="'$2'"
      shift 2
      ;;
    --update-only)
      UPDATE_ONLY="True"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

cd scripts
python3 -c "from main import main; main($DATE, $UPDATE_ONLY)"
